### ISSUE TITLE
500 with radicale 3.0.6

### ISSUE THREAD

**Issue by capocasa** [jspricke/radicale-storage#17]
Getting a 500 on any location with radicale 3.0.6.

Oct 27 12:58:06 martin env[26796]: [2020-10-27 12:58:06 +0100] [26796/Thread-3] [ERROR] An exception occurred during HEAD request on '/carlo': Error in section 'owner-write' of rights file '/etc/radicale/rights': Bad value substitution: option 'collection' in section 'owner-write' contains an interpolation key 'login' which is not a valid option name. Raw value: '^%(login)s(/.+)?$'
Oct 27 12:58:09 martin env[26796]: [2020-10-27 12:58:09 +0100] [26796/Thread-4] [ERROR] An exception occurred during HEAD request on '/carlo/caldav': Error in section 'owner-write' of rights file '/etc/radicale/rights': Bad value substitution: option 'collection' in section 'owner-write' contains an interpolation key 'login' which is not a valid option name. Raw value: '^%(login)s(/.+)?$'

**Comment by capocasa** [comment]
My bad- I had the debian system version of radicale installed (2.1) but was running the pip3 version.

**Comment by jspricke** [comment]
Hi, good thing you found the problem yourself, still I would be really interested if radicale-remind is working for you (or would need more documentation, for example) :). Also feel free to open new issues if you encounter more problems.

**Comment by capocasa** [comment]
Thank you very much, I appreciate it!

Connecting worked fine with DAVx5, but there were no calendars pre-created, and I got the following error on creating one with the DAVx5 Gui:

Oct 27 13:31:21 martin env[29284]: [2020-10-27 13:31:21 +0100] [29284/Thread-19] [ERROR] An exception occurred during MKCOL request on '/carlo/c35c4a77-598c-47b2-ad32-91ec7f141a52/': Expecting value: line 1 column 1 (char 0)

Not sure what to do from here.

**Comment by capocasa** [comment]
Just wanted to let you know after your kind help two years ago it works like a charm now and is still going strong.

**Comment by jspricke** [comment]
Awesome, thanks for writing :).
