### ISSUE TITLE
Give easy-to-follow usage example

### ISSUE THREAD

**Issue by capocasa** [jspricke/radicale-storage#20]
Please provide the canonical usage examples that doesn't require an android phone, or purchasing software- a command-line ical client that can be used from linux would work, or a cross platform desktop program like Evolution or lightning.

**Comment by jspricke** [comment]
Good idea, I added a simple example to the Readme, you can find more ways here: https://www.jujens.eu/posts/en/2015/Jan/07/curl-webdav/ do you think I should add more?
I tested it with Evolution (and lightning, I think) some time ago but it only worked with the full calendar URLs (as with curl) and did not auto discover them (but DavX5 does).
