### ISSUE TITLE
Server start fails "missing module zoneinfo"

### ISSUE THREAD

**Issue by Woastscho** [jspricke/radicale-storage#21]
[CRITICAL] An exception occurred during server startup: Failed to load storage module 'radicale_remind': No module named 'zoneinfo'
Ubuntu 20.04 radicale 3.1.5 radicale-remind 0.5.0
Any ideas ?

**Comment by jspricke** [comment]
* Woastscho ***@***.***> [2022-04-08 08:19]:
> [CRITICAL] An exception occurred during server startup: Failed to load storage module 'radicale_remind': No module named 'zoneinfo'
>Ubuntu 20.04 radicale 3.1.5 radicale-remind 0.5.0

zoneinfo is part of Python 3.9, but Ubuntu 20.04 only has 3.8.
Also note that python-remind v0.18.0 needs Remind 03.03.01 and the git 
version 04.00.00.

I would recommend a newer Ubuntu, alternatively you could try the 
backports.zoneinfo from pip and compile an newer Remind yourself.

Setting up radicale-remind could be a little tricky to get set up, I'm 
happy to help.

**Comment by Woastscho** [comment]
That fixed the problem !
Thanks for your very fast response !
