### ISSUE TITLE
Directory listings are not supported.

### ISSUE THREAD

**Issue by 532910** [jspricke/radicale-storage#4]
Can't make it work with radicale 2.1.8-1 from debian experimental
https://packages.debian.org/experimental/radicale

```
% curl http://localhost:5232/.reminders/
Directory listings are not supported.
```

```
[7fec43641700] INFO: GET request for '/.reminders/' received from 127.0.0.1 using 'curl/7.60.0'
[7fec43641700] DEBUG: Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_USER_AGENT': 'curl/7.60.0',
 'PATH_INFO': '/.reminders/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'transient',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7fec43875dc8>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7fec43641700] DEBUG: Sanitized script name: ''
[7fec43641700] DEBUG: Sanitized path: '/.reminders/'
[7fec43641700] DEBUG: Response content:
Directory listings are not supported.
[7fec43641700] INFO: GET response status for '/.reminders/' in 0.026 seconds: 403 Forbidden
```

```
% cat /etc/radicale/config | grep -v '^#' | grep -v '^$'
[server]
hosts = 0.0.0.0:5232
ssl = False
[encoding]
[auth]
type = none
[rights]
[storage]
type = radicale_remind
filesystem_folder = /var/lib/radicale
remind_file = /var/lib/radicale/.reminders
[web]
[logging]
debug = True
[headers]
```
```
% rem2ics              
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PYVOBJECT//NONSGML Version 1//EN
BEGIN:VEVENT
UID:<ID>
DTSTART;VALUE=DATE:20180331
DTEND;VALUE=DATE:20180401
DTSTAMP:20180602T060954
RDATE;VALUE=DATE:20180331,20180430,20180531,20180630,20180731,20180831,2018
 0930,20181031,20181130,20181231,20190131,20190228,20190331,20190430,201905
 31
SUMMARY:test
END:VEVENT
END:VCALENDAR
```

**Comment by jspricke** [comment]
Hi Sergio, sorry for now answering earlier I wasn't with my computer.

> % curl http://localhost:5232/.reminders/

This means you don't add a user name to authenticate. Try something like:

curl -X GET -u $USER -H "Accept: text/calendar" https://host:5232/$USER/.reminders/

> filesystem_folder = /var/lib/radicale
> remind_file = /var/lib/radicale/.reminders

This probably doesn't work. The default path for `.reminders` would be `~/.reminders`. `filesystem_folder` would then be `/home`, as proposed in the Readme and Radicale would add your username to complete the full path, as set in `remind_file`. If you want to have it in `/var/lib/radicale`, you could add a subfolder with your username, i.e. `/var/lib/radicale/$USER/.reminders`, then your `filesystem_folder` would be correct. Otherwise setting `filesystem_folder` to `/var/lib` and having `radicale` as a userame should work as well.

**Comment by 532910** [comment]
> This means you don't add a user name to authenticate.
As auth type is none. It doesn't matter as with auth the problem is the same:
```
% curl http://a:a@localhost:5232/a/.reminders
Directory listings are not supported.
```

I have both 
/var/lib/radicale/.reminders
/var/lib/radicale/a/.reminders

```
filesystem_folder = /var/lib/radicale
remind_file = /var/lib/radicale/.reminders
```

**Comment by 532910** [comment]
You'd like to say, Radicale will concatenate ```filesystem_folder + username + remind_file``` for reminders file?

As when remind_file doesn't exists i got:
```
Can't open file: /test/.reminders
Error reading /test/.reminders: Can't open file
```

**Comment by jspricke** [comment]
>```
>remind_file = /var/lib/radicale/.reminders
>```

Make this `remind_file = /var/lib/radicale/a/.reminders`

**Comment by jspricke** [comment]
Am 3. Juni 2018 13:40:52 MESZ schrieb sergio <notifications@github.com>:
>You'd like to say, Radicale will concatenate ```filesystem_folder +
>username + remind_file``` for reminders file?

No, `filesystem_folder + username = remind_file`.

>As when remind_file doesn't exists i got:
>```
>Can't open file: /test/.reminders
>Error reading /test/.reminders: Can't open file
>```

Correct.

**Comment by 532910** [comment]
```
filesystem_folder = /var/lib/radicale
remind_file = /var/lib/radicale/a/.reminders
```
```
% curl http://a:a@localhost:5232/a/.reminders
Directory listings are not supported.
```

**Comment by 532910** [comment]
> No, `filesystem_folder + username = remind_file`.

Don't understand, `remind_file` is defined in config.

**Comment by jspricke** [comment]
>```
>% curl http://a:a@localhost:5232/a/.reminders
>Directory listings are not supported.
>```

You are missing the / in the and, its:

```
% curl http://a:a@localhost:5232/a/.reminders/
```

**Comment by jspricke** [comment]
>> No, `filesystem_folder + username = remind_file`.
>
>Don't understand, `remind_file` is defined in config.

More exactly: `filesystem_folder + username + remindFilename = remind_file`

We have `remind_file` as the full path and file used for remind (we don't allow arbitrary files as a security measure). This is used to call remind. On the other end we have the path in caldav (/username/.reminders/) so we need a mapping between both. For this, the content of `filesystem_folder` is removed from the beginning of `remind_file` and the resulting string should match the caldav path.

**Comment by 532910** [comment]
OK,
```
filesystem_folder = /var/lib/radicale
remind_file = /var/lib/radicale/a/.reminders
```
```
% curl http://a:a@localhost:5232/a/.reminders/
BEGIN:VCALENDAR
...
```
works!

But how should I make per user rem file?

```
% curl http://b:b@localhost:5232/b/.reminders/
The requested resource could not be found.
```

**Comment by jspricke** [comment]
This project supports only one user for now.
