### ISSUE TITLE
has NO access to collection '.reminders'

### ISSUE THREAD

**Issue by 532910** [jspricke/radicale-storage#6]
The config sample in README.rst will give ```has NO access to collection '.reminders'```

The
```
[rights]
type = authenticated
```
should be added to fix this.

**Comment by jspricke** [comment]
No, that would mean:

| Authenticated users can read and write everything.

https://github.com/Kozea/Radicale/blob/gh-pages/configuration.md#type-1

I guess that's a workaround for not specifying a username, as commented in #4, therefor closing this.
