### ISSUE TITLE
only 3 occurances before are shown for remind monthly recurrency event

### ISSUE THREAD

**Issue by 532910** [jspricke/radicale-storage#8]
REM 1 MSG  test

test event will not be shown 2018-01-01 2018-02-01
only starting from  2018-03-01

**Comment by jspricke** [comment]
That's correct, as Remind and ICS a both complex languages, some Remind commands are evaluated first and then coverted to ICS. Feel free to send patches, if you have specific applications.
Closing, as this is arbitrary complex and working in the current implementation.

**Comment by 532910** [comment]
Please add the option to set the number of occurrences.
